### PR TITLE
Better conditions

### PR DESCRIPTION
**Pull request by bagus1**
Finally, it's ready. A massive rework of the layout engine so that routes dont have to be stored in the routes file.They now can be read from the pages table. It solidly handles nested routes!  Also, a massive reworking of testing that implements a 'common.rb' for a core shared set of tests that cuts the codebase down from 3000 lines to 1500. All tests should pass for the engine as well as for generated models.

### CODE REVIEW

**Comment by bagus1** [comment]
Um, yeah @gizard the hope would be that you make a new clone of megabar, go thru the install procedure as usual including the bit about rspec. From the megabar directory, run ```bundle exec rspec -fd``` For extra credit: Then try starting up a new myapp and creating a model (selecting 'yes' to create a page). Also then go create a field (selecting yes to the field displays and picking the proper block). Then you'd edit your new models controller_spec file to add the field name in a couple places at the top and try running that same  ```bundle exec rspec -fd``` command from the myapp dir to see if you can get your new model's tests to pass.

**Comment by gizard** [comment]
Gimme a couple days

**Comment by gizard** [comment]
Yeah wow, you're in it deep man.

**Comment by megabar** [comment]
I haven't fired this up in a while, trying now, new myapp first point of
failure, will keep at things while I can tonight.

**Pull request merged**
